export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTAL_BYID = 'FETCH_RENTAL_BYID';
export const FETCH_RENTAL_BYID_INIT = 'FETCH_RENTAL_BYID_INIT';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS ';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE ';
export const LOGOUT = 'LOGOUT ';